#!/bin/bash

if [ $DOCKER_TAG == "latest" ]
then
    docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_COMMIT
    docker push $DOCKER_REPO:$SOURCE_COMMIT
else
    docker tag $DOCKER_REPO:latest-$DOCKER_TAG $DOCKER_REPO:$SOURCE_COMMIT-$DOCKER_TAG
    docker push $DOCKER_REPO:$SOURCE_COMMIT-$DOCKER_TAG
fi