#!/bin/bash

if [ $DOCKER_TAG == "latest" ]
then
    VERSION=$(docker inspect --format='{{.Config.Labels.version}}' ${IMAGE_NAME})
    echo "Image Version: $VERSION"
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${VERSION}
    docker push ${DOCKER_REPO}:${VERSION}
else
    VERSION=$(docker inspect --format='{{.Config.Labels.version}}' ${DOCKER_REPO}:latest-${DOCKER_TAG})
    echo "Image Version: $VERSION"
    docker tag ${DOCKER_REPO}:latest-${DOCKER_TAG} ${DOCKER_REPO}:${VERSION}-${DOCKER_TAG}
    docker push ${DOCKER_REPO}:${VERSION}-${DOCKER_TAG}
fi